### ISSUE TITLE
nginx listen非80端口，游戏登录卡小黑船

### ISSUE THREAD

**Issue by RemiDre** [acgx/ooi2#17]
ooi2-access.log 卡在
"GET /kcs/mainD2.swf?api_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

supervisor的log卡在
200 GET /kcs/mainD2.swf?api_token=xxxxxxxxxxx

网页flash卡在小黑船

nginx只修改了listen处的端口
求教应怎么解决？

**Comment by xchange** [comment]
这个是mainD2.swf文件的问题，非80端口的页面上它不能正常工作
