### ISSUE TITLE
请教个环境配置问题

### ISSUE THREAD

**Issue by gitmithy** [acgx/ooi2#2]
我这已经显示安装上了python-virtualenv 是最新的了，但是在执行virtualenv -p /usr/bin/python3 --no-site-packages ooi2 这一步时却说ImportError: No module named 'virtualenv' 我去/usr/bin/virtualenv看了下确实没有这个东西，但是安装缺说最新版的了，求解这个如何解决，是pythonpath的问题吗，本来是2.7的我改成3.4的了

**Comment by gitmithy** [comment]
好吧，已解决 使用 easy_install virtualenv 安装的virtualenv

**Comment by gitmithy** [comment]
执行>>> ooi.py --port=9999 --mp的时候显示
  File "<stdin>", line 1
SyntaxError: can't assign to operator
第一次执行的时候进程都创建起来了，后面再执行就一直报这个错误

**Comment by gitmithy** [comment]
nginx应该是绑定成功了，http://kcv.miku.cf/

**Comment by kitakamiooi** [comment]
请详细说明一下你使用的环境情况。可能是由于不同的Linux发行版对Python2和3的处理不同造成的。

**Comment by Laforeta** [comment]
ubuntu 15.04版本安装时会遇到相同的问题，但是在14.04LTS上就是正常的。

**Comment by kitakamiooi** [comment]
@Laforeta 我没有用过15.04，可能是整个python系的包结构都改掉了吧

**Comment by Laforeta** [comment]
是的，而且编译pycurl这一步依然很容易出错。尝试了几个不同的debian系发行版，有些在安装python3-dev之后可以编译，有些依然报错，需要的依赖应该都有，也没有找到什么规律

```
(ooi2)root@vultr:/srv# pip install pycurl
[部分内容忽略]
In file included from src/docstrings.c:4:0:
src/pycurl.h:145:31: fatal error: openssl/crypto.h: No such file or directory
 #   include <openssl/crypto.h>
                               ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

也许把整个项目打包成轮文件或者docker容器再发布会容易一些吧。

**Comment by kitakamiooi** [comment]
@Laforeta 这个应该是缺了OpenSSL的某个开发包，whl和docker啥的我都不会呢
