### ISSUE TITLE
咨询一下cdn该如何配置 

### ISSUE THREAD

**Issue by takumashin** [acgx/ooi2#4]
配置了OOI_KCS_DOMAIN后面的域名后 静态文件都会走cdn下载文件了 但是/kcsapi/获取失败 我初次接触这个不是很明白

**Comment by kitakamiooi** [comment]
如果设置了静态文件的CDN的话，所有的api请求也会走CDN那里请求，所以需要做到两点：
1. 把CDN的域名也加入nginx的配置文件中，例如
   
   server_name www.my_ooi_domain www.my_cdn_domain;
2. 设置CDN不缓存/kcsapi/_、/kcs/mainD2.swf和/kcs/resources/image/world/_.png

**Comment by takumashin** [comment]
谢谢学姐
