### ISSUE TITLE
关于添加info.html后会报错的问题

### ISSUE THREAD

**Issue by dark-flames** [acgx/ooi2#5]
自定义info文件后上传会导致直接报错掉，错误代号是500。

**Comment by dark-flames** [comment]
貌似添加notice.html也会

**Comment by kitakamiooi** [comment]
先进debug模式看看具体的错误信息

**Comment by dark-flames** [comment]
还有一个问题是进入游戏后再刷新，刷新后点击就猫

**Comment by kitakamiooi** [comment]
刷新就猫的问题在官方10月9号更新后出现，redis分支已修复此问题

**Comment by dark-flames** [comment]
因为我使用的人很少，所以并不想开CDN，那么我依然要全部更新么。貌似上次试过，然后504

**Comment by kitakamiooi** [comment]
redis分支不一定要使用CDN的，等下我会写个页面介绍一下redis分支如何安装配置。

**Comment by dark-flames** [comment]
万分感谢

**Comment by kitakamiooi** [comment]
https://github.com/kitakamiooi/ooi2/wiki/OOI%E7%9A%84Redis%E5%88%86%E6%94%AF
