### ISSUE TITLE
关于poi的支持问题

### ISSUE THREAD

**Issue by marierose147** [acgx/ooi2#6]
![bandicam 2015-10-13 22-34-26-256](https://cloud.githubusercontent.com/assets/13193378/10458205/45714536-71fc-11e5-858a-5db960927d08.png)
如图所示，poi登录ooi的话，游戏能正常显示，但poi无法获取信息。希望大神能予以解决。

**Comment by kitakamiooi** [comment]
是否使用了安全连接？安全连接下poi无法读取信息
