### ISSUE TITLE
关于一些个人的问题

### ISSUE THREAD

**Issue by forchs** [acgx/ooi2#8]
请问只是私人用的话，有什么限制登录的方法么。。

**Comment by kitakamiooi** [comment]
可以配置Nginx服务器限制访问IP，要求HTTP Basic认证什么的

**Comment by forchs** [comment]
沃通的私钥代码是 ssl_certificate_key  
教程里给的是     ssl_private_key 
还有后面的路径是要改的 
弄了好久才明白 捂脸。。。

**Comment by HoshinoTouko** [comment]
可以用apache或者nginx的用户登录控制吧

**Comment by dark-flames** [comment]
我是直接改的代码增加了访问datebase验证用户的部分

**Comment by forchs** [comment]
谢了~
